[package]
name = "nstd"
version = "0.0.0"
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[features]
default = ["std", "nstd_core"]
std = []
clib = []
nstd_alloc = ["nstd_core", "nstd_os_windows_alloc"]
nstd_core = ["cty"]
nstd_cstring = ["nstd_core", "nstd_vec"]
nstd_heap_ptr = ["nstd_alloc", "nstd_core"]
nstd_io = []
nstd_os = []
nstd_os_windows_alloc = [
    "nstd_os", "nstd_core", "windows-sys/Win32_Foundation", "windows-sys/Win32_System_Memory"
]
nstd_shared_ptr = ["nstd_alloc", "nstd_core"]
nstd_string = ["nstd_core", "nstd_vec"]
nstd_vec = ["nstd_alloc", "nstd_core"]

[dependencies]
cty = { version = "0.2", optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.36", optional = true }
