[package]
name = "nstd"
version = "0.0.0"
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[features]
default = ["std", "nstd_core"]
std = []
nstd_core = ["cty"]

[dependencies]
cty = { version = "0.2", optional = true }
