[package]
name = "nstd-sys"
version = "0.1.3"
edition = "2021"
license = "MIT"
homepage = "https://github.com/RustEnthusiast/nstd"
repository = "https://github.com/RustEnthusiast/nstd"
description = "Cross platform general purpose C library written in Rust."
readme = "README.md"
exclude = ["include"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[features]
default = ["std", "nstd_core"]
std = []
clib = []
asm = []
nstd_alloc = ["nstd_os_windows_alloc"]
nstd_core = []
nstd_cstring = ["nstd_alloc", "nstd_core", "nstd_vec"]
nstd_heap_ptr = ["nstd_alloc", "nstd_core"]
nstd_io = ["nstd_alloc", "nstd_core", "nstd_string", "nstd_vec", "std"]
nstd_math = ["std"]
nstd_os = []
nstd_os_windows_alloc = [
    "nstd_alloc", "nstd_os", "windows-sys/Win32_Foundation", "windows-sys/Win32_System_Memory"
]
nstd_shared_lib = ["libloading", "nstd_core", "std"]
nstd_shared_ptr = ["nstd_alloc", "nstd_core"]
nstd_string = ["nstd_alloc", "nstd_core", "nstd_vec"]
nstd_vec = ["nstd_alloc", "nstd_core"]

[dependencies]
libloading = { version = "0.7", optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.36", optional = true }
