[package]
name = "nstd-sys"
version = "0.4.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/RustEnthusiast/nstd"
repository = "https://github.com/RustEnthusiast/nstd"
description = "Cross platform general purpose C library written in Rust."
readme = "README.md"
exclude = ["include"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]

[profile.release]
overflow-checks = true
panic = "abort"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[features]
default = ["std", "nstd_core"]
std = []
clib = []
asm = []
nstd_alloc = ["nstd_core", "nstd_os_unix_alloc", "nstd_os_windows_alloc"]
nstd_app = ["gilrs", "nstd_core", "nstd_heap_ptr", "nstd_string", "std", "winit"]
nstd_core = ["windows-sys?/Win32_Globalization"]
nstd_cstring = ["nstd_alloc", "nstd_core", "nstd_vec"]
nstd_env = ["nstd_core", "nstd_io", "nstd_string", "nstd_vec", "std"]
nstd_fs = ["nstd_core", "nstd_io", "nstd_string", "nstd_vec", "std"]
nstd_heap_ptr = ["nstd_alloc", "nstd_core"]
nstd_image = ["image", "nstd_core", "std"]
nstd_image_gif = ["image/gif", "nstd_image"]
nstd_image_ico = ["image/ico", "nstd_image"]
nstd_image_jpeg = ["image/jpeg", "nstd_image"]
nstd_image_png = ["image/png", "nstd_image"]
nstd_io = ["nstd_alloc", "nstd_core", "nstd_string", "nstd_vec", "std"]
nstd_math = ["std"]
nstd_os = []
nstd_os_unix_alloc = ["libc", "nstd_core", "nstd_os"]
nstd_os_unix_shared_lib = ["libc", "nstd_core", "nstd_os"]
nstd_os_windows_alloc = [
    "nstd_core", "nstd_os", "windows-sys/Win32_Foundation", "windows-sys/Win32_System_Memory"
]
nstd_os_windows_shared_lib = [
    "nstd_core", "nstd_os", "windows-sys/Win32_Foundation", "windows-sys/Win32_System_LibraryLoader"
]
nstd_os_windows_str = ["nstd_core", "nstd_os", "nstd_vec", "windows-sys/Win32_Globalization"]
nstd_proc = ["nstd_core", "nstd_io", "std"]
nstd_shared_lib = [
    "nstd_core", "nstd_cstring", "nstd_os_unix_shared_lib", "nstd_os_windows_shared_lib",
    "nstd_os_windows_str", "nstd_vec"
]
nstd_shared_ptr = ["nstd_alloc", "nstd_core"]
nstd_string = ["nstd_alloc", "nstd_core", "nstd_vec"]
nstd_thread = ["nstd_core", "nstd_heap_ptr", "nstd_io", "std"]
nstd_vec = ["nstd_alloc", "nstd_core"]
nstd_window = ["nstd_app", "nstd_core", "nstd_image", "std", "winit"]

[dependencies]
gilrs = { version = "0.10", optional = true }
image = { version = "0.24", optional = true, default-features = false }
winit = { version = "0.27", optional = true }

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2", optional = true, default-features = false }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.42", optional = true }
